"use client";
import { useState } from "react";
import { ArrowRight, Check, ChevronDown, Menu, Play, Sparkles, X } from "lucide-react";
import { motion } from "framer-motion";

const tools=[
  ["Batch Edit","Run the same AI edits across thousands of images.","01"],
  ["Image API","Automate image production and keep every listing consistent.","02"],
  ["Marketplace Sync","Publish on-brand visuals to your store and marketplace feeds.","03"],
  ["Enterprise","Custom models, dedicated capacity and SLA-backed uptime.","04"],
  ["AI Product Photography","Create studio-quality product visuals without a studio.","05"],
  ["Brand Kit","Lock colors, logos and layouts so every asset stays on brand.","06"],
  ["Instant Resize","One image, every format — ready for every channel.","07"],
  ["Video Templates","Turn a product shot into campaign-ready video.","08"],
  ["Background Remover","Fast, precise cutouts built for commerce.","09"],
  ["AI Shadow","Add realistic shadows that ground your products.","10"],
  ["Recolor","Generate new product colors while preserving detail.","11"],
  ["Product Staging","Place products into convincing scenes in seconds.","12"]
];

function Header(){const [open,setOpen]=useState(false);return <><header className="fixed top-0 left-0 right-0 z-50 nav-blur"><div className="container h-[72px] flex items-center justify-between"><a href="#" className="text-[22px] font-black tracking-[-.07em]">photoroom<span className="text-[#7357ff]">.</span></a><nav className="desktop-nav flex items-center gap-7 text-[14px] font-semibold text-[#36353a]"><a href="#product">Product</a><a href="#solutions">Solutions</a><a href="#enterprise">Enterprise</a><a href="#resources">Resources</a><a href="#pricing">Pricing</a></nav><div className="desktop-nav flex items-center gap-2"><button className="btn btn-light">Log in</button><button className="btn btn-dark">Start creating <ArrowRight size={15}/></button></div><button aria-label="Toggle menu" className="md:hidden p-2" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<div className="md:hidden bg-white border-t border-black/5 px-5 pb-5"><div className="flex flex-col gap-4 pt-4 font-semibold"><a onClick={()=>setOpen(false)} href="#product">Product</a><a onClick={()=>setOpen(false)} href="#solutions">Solutions</a><a onClick={()=>setOpen(false)} href="#enterprise">Enterprise</a><a onClick={()=>setOpen(false)} href="#resources">Resources</a><a onClick={()=>setOpen(false)} href="#pricing">Pricing</a><div className="flex gap-2 pt-2"><button className="btn btn-light flex-1">Log in</button><button className="btn btn-dark flex-1">Start creating</button></div></div></div>}</header></>}

function Hero(){return <section className="pt-[126px] pb-20 overflow-hidden"><div className="container grid lg:grid-cols-[.9fr_1.1fr] gap-14 items-center"><div className="reveal"><div className="eyebrow mb-6">AI-powered commerce creative</div><h1 className="display max-w-[680px]">Sell at <span className="gradient-text">first sight.</span></h1><p className="mt-7 text-[20px] leading-8 text-[#66656b] max-w-[550px]">The future-ready product visual solution for e-commerce. Create images that make people stop, look, and buy.</p><div className="flex flex-wrap gap-3 mt-8"><button className="btn btn-dark px-6 py-4">Start creating <ArrowRight size={17}/></button><button className="btn btn-light px-6 py-4">Contact sales</button></div><div className="mt-10 flex items-center gap-3"><div className="flex -space-x-2">{["photo-1494790108377-be9c29b29330","photo-1500648767791-00dcc994a43e","photo-1534528741775-53994a69daeb","photo-1507003211169-0a1dd7228f2d"].map(id=><img key={id} className="w-9 h-9 rounded-full border-2 border-white object-cover" src={`https://images.unsplash.com/${id}?auto=format&fit=crop&w=80&q=80`} alt=""/>)}</div><span className="text-sm font-semibold">Join 1M+ businesses selling more with Photoroom</span></div></div><div className="reveal delay-2"><HeroVisual/></div></div></section>}
function HeroVisual(){return <div className="visual hero-glow shadow-soft min-h-[500px] p-5 sm:p-8"><div className="absolute inset-0 opacity-30 dot-grid"/><div className="relative h-full min-h-[450px] flex items-center justify-center"><div className="absolute -left-2 top-12 w-36 h-48 rounded-2xl bg-white/80 backdrop-blur-md shadow-xl p-3 rotate-[-7deg]"><div className="h-full rounded-xl bg-[#ece9ff] flex items-center justify-center"><Sparkles className="text-[#7257ff]"/></div></div><div className="w-[68%] aspect-[4/5] bg-white rounded-[28px] p-3 shadow-2xl rotate-[2deg]"><div className="w-full h-full rounded-[20px] overflow-hidden bg-[#f1eee8]"><img src="https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85" alt="Product photography example" className="w-full h-full object-cover"/></div></div><div className="absolute -right-1 bottom-10 w-44 rounded-2xl bg-[#111113]/90 text-white p-4 backdrop-blur-xl shadow-xl"><div className="text-xs text-white/55">GENERATED</div><div className="font-bold mt-1">Studio scene</div><div className="mt-3 h-1 rounded-full bg-white/15"><div className="h-full w-[88%] rounded-full bg-[#ffd43b]"/></div></div></div></div>}

export function ProductGrid(){return <section id="product" className="py-24 bg-[#f6f5f7]"><div className="container"><div className="max-w-[700px]"><div className="eyebrow">The full AI visual solution</div><h2 className="h2 mt-4">A complete solution<br/>for <span className="gradient-text">every image.</span></h2><p className="mt-6 text-lg text-[#68676d] leading-7">Whether you&apos;re listing your first product or managing millions of SKUs, everything you need to create, edit and scale lives in one place.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-14">{tools.map(([name,desc,num],i)=><motion.a initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{delay:(i%3)*.05}} href="#" key={name} className="card p-6 min-h-[225px] flex flex-col group"><div className="flex justify-between items-start"><span className="w-10 h-10 rounded-full bg-[#eeeafc] flex items-center justify-center text-[#7055f4]"><Sparkles size={17}/></span><span className="text-xs font-bold text-[#aaa8af]">{num}</span></div><div className="mt-auto"><h3 className="text-[21px] font-extrabold tracking-[-.03em]">{name}</h3><p className="text-sm leading-6 text-[#747279] mt-2 max-w-[290px]">{desc}</p><span className="inline-flex mt-4 text-sm font-bold opacity-0 group-hover:opacity-100 transition-opacity">Explore <ArrowRight size={15} className="ml-1"/></span></div></motion.a>)}</div></div></section>}

export function Growth(){return <section id="solutions" className="py-28"><div className="container"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-7"><div><div className="eyebrow">One platform, every stage of growth</div><h2 className="h2 mt-4">Built around how<br/>you <span className="gradient-text">actually grow.</span></h2></div><p className="max-w-[430px] text-[#6d6b72] leading-7">From a first listing to millions of products, your visual workflow should get faster — not more complicated.</p></div><div className="grid lg:grid-cols-3 gap-4 mt-14">{[["Growing brands","Move fast without hiring a creative team.","Create scroll-stopping product visuals, test new concepts and keep your store looking consistent.","Start creating"],["Scaling businesses","Produce more without adding more work.","Batch edit catalogs, automate production and publish channel-ready assets from one workflow.","Explore automation"],["Enterprise","A visual engine built for your scale.","Custom models, dedicated capacity, governance and support for high-volume commerce teams.","Talk to sales"]].map(([t,h,d,c],i)=><div key={t} className={`rounded-[28px] p-7 min-h-[380px] ${i===1?'bg-[#111113] text-white':'bg-[#f5f3f8]'}`}><div className="text-sm font-bold opacity-60">0{i+1}</div><h3 className="text-3xl font-extrabold tracking-[-.045em] mt-16">{t}</h3><p className="font-bold text-lg mt-3">{h}</p><p className={`text-sm leading-6 mt-4 ${i===1?'text-white/60':'text-[#77747d]'}`}>{d}</p><button className={`btn mt-7 ${i===1?'bg-white text-black':'btn-dark'}`}>{c}<ArrowRight size={15}/></button></div>)}</div></div></section>}

export function Stories(){return <section className="py-24 bg-[#111113] text-white overflow-hidden"><div className="container"><div className="flex items-end justify-between gap-5"><div><div className="eyebrow text-white/50">Customer stories</div><h2 className="h2 mt-4">Less production.<br/><span className="text-[#ffd43b]">More selling.</span></h2></div><button className="btn bg-white text-black hidden sm:flex">See all stories <ArrowRight size={15}/></button></div><div className="grid lg:grid-cols-[1.2fr_.8fr] gap-5 mt-14"><div className="rounded-[28px] overflow-hidden min-h-[480px] relative bg-[#25232a]"><img className="absolute inset-0 w-full h-full object-cover opacity-80" src="https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1400&q=85" alt="Retail store"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent"/><div className="absolute bottom-0 p-8 max-w-[600px]"><div className="text-sm font-bold text-white/55">CASE STUDY</div><blockquote className="text-2xl sm:text-3xl font-bold tracking-[-.03em] mt-3">“Photoroom helped us cut image production costs by 99%.”</blockquote><div className="mt-6 font-bold">A modern commerce team</div></div></div><div className="rounded-[28px] bg-[#7156ff] p-8 min-h-[480px] flex flex-col justify-between"><div><div className="text-sm font-bold text-white/60">THE RESULT</div><div className="text-[72px] leading-none font-black tracking-[-.07em] mt-5">99%</div><div className="text-xl font-bold mt-2">lower cost per image</div></div><div><div className="h-px bg-white/20"/><p className="mt-6 text-white/75 leading-7">Give your team an AI production layer that turns product photography into a repeatable, scalable system.</p><button className="btn bg-white text-black mt-6">Read the story <ArrowRight size={15}/></button></div></div></div></div></section>}

export function Scale(){return <section className="py-28"><div className="container grid lg:grid-cols-[.8fr_1.2fr] gap-16"><div><div className="eyebrow">Built for visual production at scale</div><h2 className="h2 mt-4">The creative<br/><span className="gradient-text">operating system.</span></h2><p className="text-[#6b6970] leading-7 mt-6">A single workflow for every visual your commerce team needs — with automation underneath it.</p></div><div className="divide-y divide-[#e7e5ea]">{[["01","Create faster","Generate product imagery, campaign concepts and on-brand scenes without starting from scratch."],["02","Edit at scale","Apply background removal, resizing, shadows, recoloring and more across entire catalogs."],["03","Automate production","Connect your workflow with APIs and integrations so visual production keeps moving."],["04","Stay on brand","Centralize templates and guardrails so every marketplace image looks like you." ]].map(([n,t,d])=><div key={n} className="py-7 flex gap-6 group"><span className="text-sm font-bold text-[#9a979f]">{n}</span><div><h3 className="text-2xl font-extrabold tracking-[-.035em] group-hover:text-[#7055f4] transition-colors">{t}</h3><p className="text-[#747279] leading-6 mt-2 max-w-[600px]">{d}</p></div></div>)}</div></div></section>}

export function Showcase(){return <section className="py-24 bg-[#f6f5f7]"><div className="container"><div className="text-center max-w-[720px] mx-auto"><div className="eyebrow">See what it can do</div><h2 className="h2 mt-4">From raw product to <span className="gradient-text">ready to sell.</span></h2></div><div className="grid md:grid-cols-2 gap-5 mt-14"><div className="visual min-h-[460px] bg-[#ddd] p-5"><div className="absolute top-5 left-5 pill text-xs font-bold">AI PRODUCT PHOTOGRAPHY</div><img src="https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=85" alt="AI product photography"/><div className="absolute bottom-5 left-5 right-5 bg-white/90 backdrop-blur-md rounded-2xl p-4"><div className="font-extrabold">Turn one product shot into a campaign.</div><div className="text-sm text-[#747279] mt-1">Generate scenes, lighting and backgrounds in seconds.</div></div></div><div className="visual min-h-[460px] bg-[#222] p-5"><div className="absolute top-5 left-5 pill text-xs font-bold">BACKGROUND REMOVER</div><div className="w-full h-full min-h-[410px] rounded-2xl bg-[radial-gradient(circle_at_center,#8e7aff,#24204a_55%,#17151d)] flex items-center justify-center"><div className="w-56 h-64 rounded-3xl bg-white shadow-2xl rotate-[-4deg] p-2"><img src="https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=85" alt="Product cutout" className="w-full h-full object-cover rounded-2xl"/></div></div><div className="absolute bottom-5 left-5 right-5 bg-white/90 backdrop-blur-md rounded-2xl p-4"><div className="font-extrabold">Clean cutouts. No manual masking.</div><div className="text-sm text-[#747279] mt-1">Precise edges, transparent output, instant export.</div></div></div></div></div></section>}

export function Enterprise(){return <section id="enterprise" className="py-28"><div className="container"><div className="rounded-[34px] overflow-hidden bg-[#111113] text-white p-7 sm:p-12 lg:p-16 relative"><div className="absolute right-[-10%] top-[-35%] w-[55%] aspect-square rounded-full bg-[#7156ff]/30 blur-3xl"/><div className="relative max-w-[850px]"><div className="eyebrow text-white/45">Enterprise-grade by design</div><h2 className="h2 mt-5">Powerful enough for your catalog.<br/><span className="text-[#ffd43b]">Ready for your standards.</span></h2><p className="text-lg text-white/60 leading-7 mt-7 max-w-[650px]">Enterprise teams get the control, security and capacity needed to put AI into production responsibly.</p><div className="grid sm:grid-cols-2 gap-3 mt-10">{["SOC 2 Type 2","GDPR compliant","GCP / AWS / Cloudflare","Responsible AI"].map(x=><div key={x} className="border border-white/10 rounded-2xl p-4 flex items-center gap-3"><Check size={17} className="text-[#ffd43b]"/><span className="font-semibold">{x}</span></div>)}</div><div className="flex gap-3 mt-10"><button className="btn bg-white text-black">Contact sales <ArrowRight size={15}/></button><button className="btn border border-white/20">Trust center</button></div></div></div></div></section>}

export function Resources(){return <section id="resources" className="py-24 border-t border-[#e7e5ea]"><div className="container"><div className="flex items-end justify-between"><div><div className="eyebrow">Resources</div><h2 className="h2 mt-4">Ideas for selling<br/>better <span className="gradient-text">online.</span></h2></div><button className="btn btn-light hidden sm:flex">Explore resources <ArrowRight size={15}/></button></div><div className="grid md:grid-cols-3 gap-5 mt-14">{[["How to create product images that convert","GUIDE"],["The commerce team’s new visual stack","REPORT"],["What’s next for AI product photography","INSIGHTS"]].map(([t,k],i)=><article key={t} className="group"><div className="aspect-[1.35] rounded-[24px] overflow-hidden bg-[#eee]">{i===0?<img className="w-full h-full object-cover group-hover:scale-105 transition duration-500" src="https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?auto=format&fit=crop&w=900&q=80" alt=""/>:i===1?<div className="w-full h-full hero-glow flex items-center justify-center"><span className="text-white text-6xl font-black">+</span></div>:<div className="w-full h-full bg-[#111113] flex items-center justify-center"><Play className="text-white fill-white" size={48}/></div>}</div><div className="text-xs font-bold text-[#8d8a92] mt-5">{k}</div><h3 className="text-xl font-extrabold tracking-[-.025em] mt-2 group-hover:text-[#7055f4]">{t}</h3></article>)}</div></div></section>}

export function Footer(){return <footer className="bg-[#111113] text-white pt-16 pb-8"><div className="container"><div className="grid grid-cols-2 md:grid-cols-5 gap-10 pb-16"><div className="col-span-2 md:col-span-1"><div className="text-2xl font-black tracking-[-.07em]">photoroom<span className="text-[#7357ff]">.</span></div><p className="text-sm text-white/45 leading-6 mt-4">The visual engine for modern commerce.</p></div>{[["Tools","Background Remover","AI Product Photography","Batch Edit","AI Shadow"],["Solutions","Growing brands","Scaling businesses","Enterprise","Marketplace"],["Company","About","Careers","Blog","Contact"],["Explore","Pricing","API","Help center","Trust center"]].map(([h,...items])=><div key={h}><div className="font-bold mb-4">{h}</div><div className="flex flex-col gap-3 text-sm text-white/50">{items.map(x=><a href="#" key={x} className="hover:text-white transition">{x}</a>)}</div></div>)}</div><div className="border-t border-white/10 pt-7 flex flex-col sm:flex-row justify-between gap-4 text-xs text-white/35"><span>© 2026 Photoroom-inspired experience. Independent implementation.</span><div className="flex gap-5"><a href="#">Privacy</a><a href="#">Terms</a><a href="#">Cookies</a></div></div></div></footer>}

export function Home(){return <><Header/><main><Hero/><ProductGrid/><Growth/><Stories/><Scale/><Showcase/><Enterprise/><Resources/><section id="pricing" className="py-24"><div className="container text-center rounded-[34px] bg-[#f5f3f8] py-20 px-6"><div className="eyebrow">Ready when you are</div><h2 className="h2 mt-4">Make your next product<br/><span className="gradient-text">impossible to ignore.</span></h2><p className="text-[#716f76] mt-5">Start creating for free. Upgrade when your catalog demands it.</p><button className="btn btn-dark mt-8 px-7 py-4">Start creating <ArrowRight size={16}/></button></div></section></main><Footer/></>}

export function ToolPage({title,description,tag="AI TOOL"}:{title:string;description:string;tag?:string}){return <><Header/><main className="pt-[72px]"><section className="py-24"><div className="container grid lg:grid-cols-2 gap-14 items-center"><div><div className="eyebrow">{tag}</div><h1 className="display mt-5">{title}</h1><p className="text-xl text-[#6d6b72] leading-8 mt-7 max-w-[570px]">{description}</p><div className="flex gap-3 mt-8"><button className="btn btn-dark">Start creating <ArrowRight size={16}/></button><button className="btn btn-light">See examples</button></div></div><div className="visual hero-glow min-h-[480px] p-6"><div className="h-full min-h-[430px] rounded-[24px] bg-white/10 border border-white/20 backdrop-blur-md flex items-center justify-center"><div className="w-[58%] aspect-[4/5] rounded-3xl bg-white p-3 shadow-2xl"><div className="w-full h-full rounded-2xl bg-[#eee] flex items-center justify-center"><Sparkles className="text-[#7357ff]" size={45}/></div></div></div></div></div></section><ProductGrid/><Enterprise/></main><Footer/></>}
